/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

opensearchplugin {
    description = 'Local index search REST adapter'
    classname = 'org.opensearch.index.rest.search.IndexSearchApiPlugin'
    extendedPlugins = ['index-service', 'search-api']
}
repositories {
    mavenLocal()
    maven { url = "https://ci.opensearch.org/ci/dbc/snapshots/maven/" }
    mavenCentral()
}
testingConventions.enabled = false
dependencies {
    compileOnly project(':libs:index-api')
    compileOnly project(':libs:engine-api')
    compileOnly project(':modules:rest:spi')
    testImplementation project(':modules:index-service')
    testImplementation project(':modules:index-management-api')
    testImplementation project(':modules:index-indexing-api')
    testImplementation project(':modules:engine')
    testImplementation project(':modules:lucene-engine')
    testImplementation project(':modules:rest')
    testImplementation project(':modules:search-api')
    testImplementation project(':modules:indexing-api')
    testImplementation project(':modules:management-api')
    testRuntimeOnly libs.lucene.codecs
    testImplementation libs.bundles.unit.test
}
