/* SPDX-License-Identifier: Apache-2.0 */
apply plugin: 'opensearch.build'
base { archivesName = 'os-lite-core' }
repositories {
    mavenLocal()
    maven { url = 'https://ci.opensearch.org/ci/dbc/snapshots/maven/' }
    mavenCentral()
}
dependencies {
    api "org.opensearch:opensearch-common:${project.version}"
    api libs.jackson.core
    api libs.log4japi
    testImplementation libs.junit
    testImplementation libs.hamcrest
}
testingConventions.enabled = false
tasks.named('dependencyLicenses').configure { enabled = false }
tasks.named('forbiddenApisMain').configure { replaceSignatureFiles 'jdk-signatures' }
tasks.named('forbiddenApisTest').configure { replaceSignatureFiles 'jdk-signatures' }
